# install.ps1 — GitHub Copilot adapter for presentation-skill-pack
# Writes to the CURRENT directory (project-scoped instructions).
# Usage:  $env:PSP_CORE_DIR = "<path>"; .\install.ps1 [full|lite]
param([string]$Mode = "full")

$ErrorActionPreference = "Stop"

if (-not $env:PSP_CORE_DIR) {
    throw "PSP_CORE_DIR must be set to the @presentation-skill-pack/core directory"
}

$CopilotDir  = ".github"
$CopilotFile = Join-Path $CopilotDir "copilot-instructions.md"
$VsCodeDir   = ".vscode"
$McpFile     = Join-Path $VsCodeDir "mcp.json"

Write-Host "presentation-skill-pack > copilot adapter"
Write-Host "  mode:   $Mode"
Write-Host "  target: $(Get-Location)\$CopilotFile"
Write-Host ""

# ── write .github/copilot-instructions.md ────────────────────────────────────
New-Item -ItemType Directory -Force -Path $CopilotDir | Out-Null

$skillContent = Get-Content (Join-Path $env:PSP_CORE_DIR "SKILL.md") -Raw
# Strip YAML front-matter
$skillBody = ($skillContent -split '(?m)^---\r?\n')[2..($skillContent.Split('---').Length)] -join '---'
if ($skillContent -match '(?ms)^---.*?^---\r?\n(.*)') {
    $skillBody = $Matches[1]
} else {
    $skillBody = $skillContent
}

$header = "<!-- generated by @presentation-skill-pack/install copilot — do not edit by hand -->`n"
Set-Content -Path $CopilotFile -Value ($header + $skillBody) -NoNewline

Write-Host "  OK  $CopilotFile written"

# ── full mode: register MCP server in .vscode/mcp.json ───────────────────────
if ($Mode -eq "full") {
    New-Item -ItemType Directory -Force -Path $VsCodeDir | Out-Null

    if (Test-Path $McpFile) {
        $cfg = Get-Content $McpFile -Raw | ConvertFrom-Json
    } else {
        $cfg = [PSCustomObject]@{ servers = [PSCustomObject]@{} }
    }

    $cfg.servers | Add-Member -Force -NotePropertyName "presentation-skill-pack" -NotePropertyValue ([PSCustomObject]@{
        type    = "stdio"
        command = "npx"
        args    = @("@presentation-skill-pack/mcp-server")
    })

    $cfg | ConvertTo-Json -Depth 10 | Set-Content $McpFile

    Write-Host "  OK  MCP server registered in $McpFile"
}

Write-Host ""
Write-Host "Done. Open GitHub Copilot Chat in VS Code — the skill is now in context."
if ($Mode -eq "lite") {
    Write-Host "  (lite mode — MCP server not registered)"
}
