#!/usr/bin/env bash
# install.sh — GitHub Copilot adapter for presentation-skill-pack
# Writes to the CURRENT directory (project-scoped instructions).
# Usage:  PSP_CORE_DIR=<path> bash install.sh [full|lite]
set -euo pipefail

MODE="${1:-full}"
: "${PSP_CORE_DIR:?PSP_CORE_DIR must be set to the @presentation-skill-pack/core directory}"

COPILOT_DIR=".github"
COPILOT_FILE="$COPILOT_DIR/copilot-instructions.md"
VSCODE_DIR=".vscode"
MCP_FILE="$VSCODE_DIR/mcp.json"

echo "presentation-skill-pack › copilot adapter"
echo "  mode:   $MODE"
echo "  target: $(pwd)/$COPILOT_FILE"
echo ""

# ── write .github/copilot-instructions.md ────────────────────────────────────
mkdir -p "$COPILOT_DIR"

# Strip the YAML front-matter from SKILL.md before embedding.
SKILL_BODY=$(awk '
  /^---$/ && !seen { seen=1; in_front=1; next }
  in_front && /^---$/ { in_front=0; next }
  !in_front { print }
' "$PSP_CORE_DIR/SKILL.md")

cat > "$COPILOT_FILE" <<EOF
<!-- generated by @presentation-skill-pack/install copilot — do not edit by hand -->
$SKILL_BODY
EOF

echo "  ✓  $COPILOT_FILE written"

# ── full mode: register MCP server in .vscode/mcp.json ───────────────────────
if [ "$MODE" = "full" ]; then
  mkdir -p "$VSCODE_DIR"

  if [ -f "$MCP_FILE" ]; then
    EXISTING=$(cat "$MCP_FILE")
    UPDATED=$(node -e "
      const cfg = JSON.parse(process.argv[1]);
      cfg.servers = cfg.servers || {};
      cfg.servers['presentation-skill-pack'] = {
        type: 'stdio',
        command: 'npx',
        args: ['@presentation-skill-pack/mcp-server']
      };
      process.stdout.write(JSON.stringify(cfg, null, 2));
    " "$EXISTING")
    printf '%s\n' "$UPDATED" > "$MCP_FILE"
  else
    cat > "$MCP_FILE" <<'JSON'
{
  "servers": {
    "presentation-skill-pack": {
      "type": "stdio",
      "command": "npx",
      "args": ["@presentation-skill-pack/mcp-server"]
    }
  }
}
JSON
  fi
  echo "  ✓  MCP server registered in $MCP_FILE"
fi

echo ""
echo "Done. Open GitHub Copilot Chat in VS Code — the skill is now in context."
if [ "$MODE" = "lite" ]; then
  echo "  (lite mode — MCP server not registered)"
fi
